name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile2 --tag alex1ibar/activity3-development-data:latest
    - name: Push the Docker image
      run: docker push alex1ibar/activity3-development-data:latest
  publish:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Clean docker
      run: |
        docker container prune -f
        docker image prune -f
        docker rmi -f alex1ibar/activity3-development-data:latest || true
    - name: Run docker image
      run: docker run -d -p 5000:5000 alex1ibar/activity3-development-data:latest
    
